model: ~/Development/models/microsoft_Phi-3-mini-4k-instruct-gguf/Phi-3-mini-4k-instruct-q4.gguf
contextSize: 4096
useMMap: false
#interactive: false
#interactiveFirst: true
displayPrompt: false
antiPrompts:
  - <|user|>
endOfTextPrompts:
  - <|end|>
template: |-
  <|user|>
  %s<|end|>
  <|assistant|>